In [23]:
#important libraries 

In [720]:
import pandas as pd
from skimage.io import imread, imshow
from skimage import filters
from skimage import feature
from skimage.filters import prewitt_h, prewitt_v
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import f1_score
from sklearn.metrics import classification_report
from sklearn import metrics
from sklearn.model_selection import train_test_split
import numpy as np
import pickle as P
import re as CLEAN
import os
from skimage.transform import resize
from csv import writer
from PIL import ImageFile
ImageFile.LOAD_TRUNCATED_IMAGES = True
from sklearn.model_selection import train_test_split
import librosa
import warnings
warnings.filterwarnings('ignore')
from nltk.corpus import stopwords
stop = stopwords.words('english')
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import LabelEncoder
from sklearn.tree import DecisionTreeClassifier
import pickle
from textblob import TextBlob
import textblob
from sklearn.preprocessing import OneHotEncoder
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
import skimage
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import RandomForestClassifier
from collections import OrderedDict
from sklearn.ensemble import VotingClassifier

In [24]:
#load images 

In [721]:
df_ = pd.read_csv('labels.csv')
del df_['text_ocr']
del df_['Unnamed: 0']
df_

image_name                                     text_corrected  \
0        image_1.jpg  LOOK THERE MY FRIEND LIGHTYEAR NOW ALL SOHALIK...   
1       image_2.jpeg  The best of #10 YearChallenge! Completed in le...   
2        image_3.JPG  Sam Thorne @Strippin ( Follow Follow Saw every...   
3        image_4.png              10 Year Challenge - Sweet Dee Edition   
4        image_5.png  10 YEAR CHALLENGE WITH NO FILTER 47 Hilarious ...   
...              ...                                                ...   
6987  image_6988.jpg  Tuesday is Mardi Gras Wednesday is Valentine's...   
6988  image_6989.jpg  MUST WATCH MOVIES OF 2017 ITI Chennai memes MA...   
6989  image_6990.png  LESS MORE TALKING PLANNING SODA JUNK FOOD COMP...   
6990  image_6991.jpg  When I have time is a fantasy. no one has time...   
6991  image_6992.jpg  The starting point for every good idea is "Wha...   

     overall_sentiment  
0        very_positive  
1        very_positive  
2             positive  
3             positive  
4              neutral  
...                ...  
6987           neutral  
6988           neutral  
6989          positive  
6990     very_positive  
6991          positive  

[6992 rows x 3 columns]

In [694]:
path = (r'C:\Users\Abdul Haque\images\\')
images_paths = os.listdir(path)
images=[]

for files in images_paths:
    read_ = imread(path + files, as_gray = True)
    read_ = resize(read_, (200, 200))
    read_ = feature.canny(read_)
    read_ = list(read_.flatten())
    images.append(read_)

In [695]:
file = open('numeric.pkl', 'wb')
pickle.dump(images, file)
file.close()

In [722]:
file = open('numeric.pkl', 'rb')
images_data = pickle.load(file)
file.close()

In [715]:
df_image = pd.DataFrame()
df_image.insert(0, 'image_name', df_['image_name'])
df_image.insert(1, 'numeric_data', images_data)
df_image.insert(2, 'overall_sentiment', df_['overall_sentiment'])
df_image

image_name                                       numeric_data  \
0        image_1.jpg  [False, False, False, False, False, False, Fal...   
1       image_2.jpeg  [False, False, False, False, False, False, Fal...   
2        image_3.JPG  [False, False, False, False, False, False, Fal...   
3        image_4.png  [False, False, False, False, False, False, Fal...   
4        image_5.png  [False, False, False, False, False, False, Fal...   
...              ...                                                ...   
6987  image_6988.jpg  [False, False, False, False, False, False, Fal...   
6988  image_6989.jpg  [False, False, False, False, False, False, Fal...   
6989  image_6990.png  [False, False, False, False, False, False, Fal...   
6990  image_6991.jpg  [False, False, False, False, False, False, Fal...   
6991  image_6992.jpg  [False, False, False, False, False, False, Fal...   

     overall_sentiment  
0        very_positive  
1        very_positive  
2             positive  
3             positive  
4              neutral  
...                ...  
6987           neutral  
6988           neutral  
6989          positive  
6990     very_positive  
6991          positive  

[6992 rows x 3 columns]

In [723]:
df_images = []

for image in df_image.index:
    df_images.append(df_image['numeric_data'].loc[i])

In [740]:
d={'very_positive':1,'positive':1, 'very_negative':-1, 'negative':-1, 'neutral':0}
df_image["overall_sentiment"]=df_image["overall_sentiment"].map(d)

X = df_images
y = df_image.overall_sentiment

le = LabelEncoder()
y = le.fit_transform(y)
X_train_1, X_test_1, y_train_1, y_test_1 = train_test_split(X, y, test_size=0.2, random_state = 51)

In [659]:
df = pd.read_csv('labels.csv')
del df['text_ocr']
del df['Unnamed: 0']
df

image_name                                     text_corrected  \
0        image_1.jpg  LOOK THERE MY FRIEND LIGHTYEAR NOW ALL SOHALIK...   
1       image_2.jpeg  The best of #10 YearChallenge! Completed in le...   
2        image_3.JPG  Sam Thorne @Strippin ( Follow Follow Saw every...   
3        image_4.png              10 Year Challenge - Sweet Dee Edition   
4        image_5.png  10 YEAR CHALLENGE WITH NO FILTER 47 Hilarious ...   
...              ...                                                ...   
6987  image_6988.jpg  Tuesday is Mardi Gras Wednesday is Valentine's...   
6988  image_6989.jpg  MUST WATCH MOVIES OF 2017 ITI Chennai memes MA...   
6989  image_6990.png  LESS MORE TALKING PLANNING SODA JUNK FOOD COMP...   
6990  image_6991.jpg  When I have time is a fantasy. no one has time...   
6991  image_6992.jpg  The starting point for every good idea is "Wha...   

     overall_sentiment  
0        very_positive  
1        very_positive  
2             positive  
3             positive  
4              neutral  
...                ...  
6987           neutral  
6988           neutral  
6989          positive  
6990     very_positive  
6991          positive  

[6992 rows x 3 columns]

In [608]:
df['text_corrected'] = df['text_corrected'].str.replace('\d+', '')
df['text_corrected'] = df['text_corrected'].str.lower()
df['text_corrected'].astype(str).apply(lambda x: x.encode('latin-1', 'ignore').decode('latin-1'))
df['text_corrected'] = df['text_corrected'].str.replace('[^\w\s]','')
df['text_corrected'] = df['text_corrected'].str.replace('\s+',' ')
df['text_corrected'] = df['text_corrected'].astype(str)
df['text_corrected'].apply(lambda x: ' '.join([word for word in x.split() if word not in (stop)]))
df

image_name                                     text_corrected  \
0        image_1.jpg  look there my friend lightyear now all sohalik...   
1       image_2.jpeg  the best of yearchallenge completed in less th...   
2        image_3.JPG  sam thorne strippin follow follow saw everyone...   
3        image_4.png                   year challenge sweet dee edition   
4        image_5.png   year challenge with no filter hilarious year ...   
...              ...                                                ...   
6987  image_6988.jpg  tuesday is mardi gras wednesday is valentines ...   
6988  image_6989.jpg  must watch movies of iti chennai memes maanaga...   
6989  image_6990.png  less more talking planning soda junk food comp...   
6990  image_6991.jpg  when i have time is a fantasy no one has time ...   
6991  image_6992.jpg  the starting point for every good idea is what...   

     overall_sentiment  
0        very_positive  
1        very_positive  
2             positive  
3             positive  
4              neutral  
...                ...  
6987           neutral  
6988           neutral  
6989          positive  
6990     very_positive  
6991          positive  

[6992 rows x 3 columns]

In [597]:
import nlpaug.augmenter.word as naw
cleaned_text = []
for i in range(len(df['text_corrected'])):
    text = df.text_corrected[i]
    syn_aug = naw.SynonymAug(aug_src='wordnet',aug_max=4)
    syn_aug_text = syn_aug.augment(text,n=1)
    cleaned_text.append(''.join(syn_aug_text))
    
df['text_corrected'] = cleaned_text
df

image_name                                     text_corrected  \
0        image_1.jpg  spirit friend lightyear sohalikut trend play y...   
1       image_2.jpeg  best yearchallenge fill in less years kudus na...   
2        image_3.JPG  sam thorne strippin follow follow saw everyone...   
3        image_4.png                 year challenge sweet dee variation   
4        image_5.png  twelvemonth challenge filter hilarious year ch...   
...              ...                                                ...   
6987  image_6988.jpg  tuesday mardi gras wednesday valentines friday...   
6988  image_6989.jpg  must watch movies iti chennai memes maanagaram...   
6989  image_6990.png  less talk planning soda junk food complaining ...   
6990  image_6991.jpg  time fantasize one time unless make time arhti...   
6991  image_6992.jpg  begin pointedness every good idea arhtistic li...   

     overall_sentiment  
0        very_positive  
1        very_positive  
2             positive  
3             positive  
4              neutral  
...                ...  
6987           neutral  
6988           neutral  
6989          positive  
6990     very_positive  
6991          positive  

[6992 rows x 3 columns]

In [609]:
d={'very_positive':1,'positive':1, 'very_negative':-1, 'negative':-1, 'neutral':0}
df["overall_sentiment"]=df["overall_sentiment"].map(d)
X = df.text_corrected
y = df.overall_sentiment

le = LabelEncoder()
y = le.fit_transform(y)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state = 51)# 70% training and 30% test

In [610]:
vectorizer = TfidfVectorizer(ngram_range = (1, 2))
X_trainn = vectorizer.fit_transform(X_train)
X_testt = vectorizer.transform(X_test)

In [555]:
#DECISION TREE MODEL

In [615]:
clf = DecisionTreeClassifier()
clf.fit(X_trainn,y_train)
y_pred=clf.predict(X_testt)
print('Accuracy:', accuracy_score(y_test, y_pred)*100)
print("F1 Score: ",f1_score(y_test, y_pred,average='macro')*100) 
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test,y_pred))

Accuracy: 49.10650464617584
F1 Score:  36.03206217304233
              precision    recall  f1-score   support

           0       0.11      0.10      0.11       134
           1       0.34      0.36      0.35       418
           2       0.63      0.62      0.62       847

    accuracy                           0.49      1399
   macro avg       0.36      0.36      0.36      1399
weighted avg       0.49      0.49      0.49      1399

[[ 14  44  76]
 [ 36 151 231]
 [ 75 250 522]]


In [616]:
# Saving model
import pickle
Pkl_Filename = "Pickle_decision_tree_Model.pkl"  

with open(Pkl_Filename, 'wb') as file:  
    pickle.dump(clf, file)

In [617]:
# Load the Model back from file
with open(Pkl_Filename, 'rb') as file:  
    Pickled_tree_Model = pickle.load(file)

Pickled_tree_Model

DecisionTreeClassifier()

In [618]:
# Calculate the Score 
score = Pickled_tree_Model.score(X_testt, y_test)  
# Print the Score
print("Test score: {0:.2f} %".format(100 * score))  

# Predict the Labels using the reloaded Model
Ypredict = Pickled_tree_Model.predict(X_testt)  

Ypredict

Test score: 49.11 %


array([0, 1, 2, ..., 2, 2, 1], dtype=int64)

In [619]:
clf = LogisticRegression(solver = 'newton-cg', class_weight = 'balanced')
clf.fit(X_trainn,y_train)
y_pred=clf.predict(X_testt)
print('Accuracy:', accuracy_score(y_test, y_pred)*100)
print("F1 Score: ",f1_score(y_test, y_pred,average='macro')*100) 
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test,y_pred))

Accuracy: 51.1794138670479
F1 Score:  36.78278971897998
              precision    recall  f1-score   support

           0       0.13      0.10      0.12       134
           1       0.34      0.33      0.34       418
           2       0.63      0.66      0.65       847

    accuracy                           0.51      1399
   macro avg       0.37      0.37      0.37      1399
weighted avg       0.50      0.51      0.50      1399

[[ 14  38  82]
 [ 35 139 244]
 [ 57 227 563]]


In [620]:
# Saving model
import pickle
Pkl_Filename = "Pickle_LogisticRegression_Model.pkl"  

with open(Pkl_Filename, 'wb') as file:  
    pickle.dump(clf, file)

file.close()

In [621]:
import pickle
Pkl_Filename = "Pickle_LogisticRegression_Model.pkl"  

with open(Pkl_Filename, 'rb') as file:  
    LogisticRegression_model = pickle.load(file)
    
LogisticRegression_model

LogisticRegression(class_weight='balanced', solver='newton-cg')

In [622]:
# Calculate the Score 
score = LogisticRegression_model.score(X_testt, y_test)  
# Print the Score
print("Test score: {0:.2f} %".format(100 * score))  

# Predict the Labels using the reloaded Model
Ypredict = LogisticRegression_model.predict(X_testt)  

Ypredict

Test score: 51.18 %


array([2, 1, 2, ..., 2, 2, 2], dtype=int64)

In [677]:
clf = KNeighborsClassifier(n_neighbors = 1, weights = 'distance', p = 2)
clf.fit(X_trainn,y_train)
y_pred=clf.predict(X_testt)
print('Accuracy:', accuracy_score(y_test, y_pred)*100)
print("F1 Score: ",f1_score(y_test, y_pred,average='macro')*100) 
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test,y_pred))

Accuracy: 49.035025017869906
F1 Score:  35.286954594354974
              precision    recall  f1-score   support

           0       0.09      0.07      0.08       134
           1       0.34      0.38      0.36       418
           2       0.63      0.61      0.62       847

    accuracy                           0.49      1399
   macro avg       0.35      0.35      0.35      1399
weighted avg       0.49      0.49      0.49      1399

[[ 10  48  76]
 [ 29 157 232]
 [ 67 261 519]]


In [645]:
# Saving model
import pickle
Pkl_Filename = "Pickle_KNNeighbors_Model.pkl"  

with open(Pkl_Filename, 'wb') as file:  
    pickle.dump(clf, file)

file.close()

In [646]:
with open(Pkl_Filename, 'rb') as file:  
    KNN_model = pickle.load(file)
    
KNN_model

KNeighborsClassifier(n_neighbors=1)

In [681]:
All = VotingClassifier(estimators = [('tree',Pickled_tree_Model), ('knn',KNN_model), ('logistic',LogisticRegression_model)])

In [682]:
All.fit(X_trainn, y_train)
predic = All.predict(X_testt)

In [683]:
print('Accuracy:', accuracy_score(y_test, predic)*100)
print("F1 Score: ",f1_score(y_test, predic,average='macro')*100) 
print(classification_report(y_test, predic))
print(confusion_matrix(y_test,predic))

Accuracy: 50.464617583988556
F1 Score:  36.27998885750749
              precision    recall  f1-score   support

           0       0.13      0.12      0.12       134
           1       0.33      0.30      0.32       418
           2       0.63      0.66      0.65       847

    accuracy                           0.50      1399
   macro avg       0.36      0.36      0.36      1399
weighted avg       0.49      0.50      0.50      1399

[[ 16  39  79]
 [ 41 127 250]
 [ 70 214 563]]
